$lock = pidof hyprlock || hyprlock
$suspend = systemctl suspend

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 180
        on-timeout = $lock
    on-resume = notify-send -t 5000 -u low "Welcome Back" "Resuming system processes" -i /usr/share/icons/system.png
}

listener {
    timeout = 360
        on-timeout = $suspend
}
